export const ALL_INFO_REQUEST = "ALL_INFO_REQUEST";
export const ALL_INFO_SUCCESS = "ALL_INFO_SUCCESS";
export const ALL_INFO_FAIL = "ALL_INFO_FAIL";

export const INFO_DETAILS_REQUEST = "INFO_DETAILS_REQUEST";
export const INFO_DETAILS_SUCCESS = "INFO_DETAILS_SUCCESS";
export const INFO_DETAILS_FAIL = "INFO_DETAILS_FAIL";

export const NEW_INFO_REQUEST = "NEW_INFO_REQUEST";
export const NEW_INFO_SUCCESS = "NEW_INFO_SUCCESS";
export const NEW_INFO_RESET = "NEW_INFO_RESET";
export const NEW_INFO_FAIL = "NEW_INFO_FAIL";

export const ADMIN_INFO_REQUEST = "ADMIN_INFO_REQUEST";
export const ADMIN_INFO_SUCCESS = "ADMIN_INFO_SUCCESS";
export const ADMIN_INFO_FAIL = "ADMIN_INFO_FAIL";

export const DELETE_INFO_REQUEST = "DELETE_INFO_REQUEST";
export const DELETE_INFO_SUCCESS = "DELETE_INFO_SUCCESS";
export const DELETE_INFO_RESET = "DELETE_INFO_RESET";
export const DELETE_INFO_FAIL = "DELETE_INFO_FAIL";

export const UPDATE_INFO_REQUEST = "UPDATE_INFO_REQUEST";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL";
export const UPDATE_INFO_RESET = "UPDATE_INFO_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 